-- CREATING TABLE ALUNOS
CREATE TABLE alunos(
	id SERIAL,
	nome VARCHAR(255),
	cpf CHAR(11),
	observacao TEXT,
	idade INTEGER,
	dinheiro NUMERIC(10,2),
	altura REAL,
	ativo BOOLEAN,
	data_nascimento DATE,
	hora_aula TIME,
	matriculado_em TIMESTAMP
);

-- RETRIEVING ALL DATA FROM ALUNOS
SELECT * FROM alunos;

-- INSERTING DATA IN TABLE ALUNOS
INSERT INTO alunos(nome, cpf, observacao, idade, dinheiro, altura, ativo, data_nascimento, hora_aula, matriculado_em)
VALUES ('Matheus', '27298219022', 'aaaaaaaaaa', 19, 100.50, 1.82, TRUE, '2003-09-08', '19:20:00', '2020-01-01 12:00:00');

-- RETRIEVING DATA WITH CONDITION USING CLAUSULE WHERE
SELECT * FROM alunos WHERE id = 1;

-- UPDATING ROW IN TABLE ALUNO
UPDATE alunos
SET nome = 'Matheus Canovas'
WHERE id = 2;

-- DELETING ROW IN TABLE ALUNOS
DELETE FROM alunos WHERE cpf = '27298219022';

-- SELECTING SPECIFICS COLUMNS IN TABLE ALUNOS
SELECT id, nome FROM alunos;

-- SELECTING SPECIFICS COLUMNS IN TABLE ALUNOS AND SET ALIAS TO COLUMN
SELECT id, nome AS nome_completo FROM alunos;

-- WORKING WITH FILTERS
SELECT * FROM alunos WHERE nome <> 'Matheus Canovas';
-- THE <> MEANS !=

SELECT * FROM alunos WHERE nome LIKE '_atheus';
-- THE _ MEANS THAT ISN'T MATTER WHAT IS THE FIRST LETTER, BUT, THE REST OF STRING NEEDS TO CONTAINS 'ATHEUS'

SELECT * FROM alunos WHERE nome LIKE 'Mat%'
-- THE % MEANS THAT THE VALUE OF COLUMN 'NAME' NEEDS TO START WITH 'MAT' AND WHATEVER COMES AFTER THE %, IT'S LIKE A JOKER

SELECT * FROM alunos WHERE nome NOT LIKE 'Matheus';
-- RETRIEVE ALL ROWS THAT THE COLUMN 'NOME' DO NOT CONTAINS 'MATHEUS' VALUE, ITS LIKE A <> BUT MORE EXPLICT

SELECT * FROM alunos WHERE cpf IS NULL;

SELECT * FROM alunos WHERE cpf IS NOT NULL;
-- WHEN WE WORK WITH COLUMNS THAT CONTAINS NULL VALUE, WE NEED TO WORK WITH 'IS NUL'L AND 'IS NOT NULL', BECAUSE THE '= NULL' DO NOT EXIST!

